# --- Steam Fixes ---

# 1. Force Main Steam Window to TILE
# We use 'float 0' and 'tile 1' to force tiling.
windowrule = float 0, match:class ^(steam)$, match:title ^(Steam)$
windowrule = tile 1, match:class ^(steam)$, match:title ^(Steam)$

# 2. Ensure popups float (Friends, Settings, etc.)
windowrule = float 1, match:class ^(steam)$, match:title ^(Friends List|Settings|Properties)$

# --- Game Fixes (Excluding Steam) ---

# 1. Force Opacity (Fixes transparent/ghostly games)
windowrule = opacity 1.0 override 1.0 override, match:xwayland 1

# 2. Force Fullscreen (Hides Waybar) for Games
windowrule = fullscreen 1, match:xwayland 1, match:class negative:^(steam)$

# --- Waybar glassmorphism ---
waybarlayerrle = ignorealpha 0.4
blurls = waybar
